# API Framework Details
proxyHost=proxy.applepersonatomcar.elephanttarzenneutral.com
proxyPort=8080
runLocally=Yes
environment.filepath=.//src//test/resources//environments//
apiExpectedBody.filePath=.//src//test/resources//data//output//ExpectedResponseBody//
apiRequestBody.filePath=.//src//test/resources//data//input//apiRequestBody//
# Zephyr Connector Details
zephyrBaseUrl=https://prod-play.zephyr4jiracloud.com/connect
zapiAccessKey=accessKeyFromYourJiraProfilePage
zapiSecretKey=secretKeyFromJiraProfilePage
accountId=fromJiraUrl
zephyr.connectionFlag=Yes
zephyr.executionFlag=Yes
zephyr.projectId=12345
zephyr.versionId=67890
zephyr.cycleName=Zephyr Test Cycle
zephyr.folderName=Zephyr Test Folder
zephyr.JSONBody.testList=["JIRA-12345","JIRA-67890"]