# Serenity Frameworks WebDriver Waits
webDriver.timeouts.implicitlyWait=15000
webDriver.timeouts.fluentWait=15000
story.timeout.in.secs=5000

# API Framework Details
proxyHost=proxy.applepersonatomcar.elephanttarzenneutral.com
proxyPort=8080
runLocally=Yes
environment.filepath=.//src//test/resources//environments//
apiExpectedBody.filePath=.//src//test/resources//data//output//ExpectedResponseBody//
apiRequestBody.filePath=.//src//test/resources//data//input//apiRequestBody//
# Zephyr Connector Details
zephyrBaseUrl=https://prod-play.zephyr4jiracloud.com/connect
zapiAccessKey=accessKeyFromYourJiraProfilePage
zapiSecretKey=secretKeyFromJiraProfilePage
accountId=fromJiraUrl
zephyr.connectionFlag=Yes
zephyr.executionFlag=No
zephyr.projectId=12345
zephyr.versionId=67890
zephyr.cycleName=Zephyr Test Cycle
zephyr.folderName=Zephyr Test Folder
zephyr.JSONBody.testList=["JIRA-12345","JIRA-67890"]
# Okta token automatic fetch details
okta.appEnvironment=Dev
okta.issuerId_DEV=aus7something
okta.issuerId_QA=aus1something
okta.clientId_DEV=0oa7something
okta.clientId_QA=0oa1something
okta.redirectUri_Stage=https://company-stage-domain.com/login/callback
okta.redirectUri_Prod=https://company-prod-domain.com/login/callback
okta.codeChallenge=qaztsomething
okta.codeVerifier=aoL1something
oktaAuthRequest.filePath=.//src//test/resources//data//input//
# Environment independent data generation
environmentData.createFile=Yes
# Azure Application Insights Key
appInsights.instrumentationKey = someGuidForAzureAccess
# Jira Defect Creation
jira.userName=abc@xyz.com
jira.apiKey=generatedFromUserProfile
jira.filePath=.//src//test/resources//data//input//
jira.connectionFlag=No
jira.defectCreationFlag=No
# Chrome Driver Path
chrome.capabilities.acceptInsecureCerts=true
webdriver.chrome.driver=.//src//test/resources//drivers//chromedriver.exe
# Locators file paths
locators.filePath.android=.//src//test/resources//locators/Android.json
locators.filePath.ios=.//src//test/resources//locators/iOS.json
locators.filePath.web=.//src//test/resources//locators/Web.json
ExecutionType=web
# Upload images
image.png=.//src//test/resources//images//Proto.png
image.jpg=.//src//test/resources//images//Proto.jpg
image.svg=.//src//test/resources//images//Proto.svg
image.excel=.//src//test/resources//images//Proto.xlsx
image.doc=.//src//test/resources//images//Proto.doc
image.jpeg=.//src//test/resources//images//Proto.jpeg
image.txt=.//src//test/resources//images//Proto.txt
image.gif=.//src//test/resources//images//Proto.gif
image.pdf=.//src//test/resources//images//Proto.pdf
# Mobile Testing Configuration
appium.hub=http://127.0.0.1:4723/wd/hub
appium.ipAddress=127.0.0.1
appium.port=4723

appium.deviceName=ANDROID_MOBILE_ID
appium.platformVersion=ANDROID_VERSION
appium.platformName=android
!-- In order to restore the application session keep full reset false and no reset true
!-- Like user enter details and OTP comes on web. User copy that OTP and paste in app at same position
appium.noReset=false
appium.unicodeKeyboard=true
appium.resetKeyboard=true
appium.appPackage=com.Company.Qwerty
appium.appActivity=com.Company.Qwerty.MainActivity
appium.automationName=UIAutomator2
appium.autoGrantPermission=true
appium.fullReset=false
appium.fullResetWeb=false
appium.mailBoxUrl=https://somemailbox.com/
appium.newCommandTimeOut=100

appium.iosDeviceName=iOS_Mobile_ID
appium.iosMobileName=iPhone
appium.iosPlatformVersion=iOS_Version
appium.iosPlatformName=iOS
appium.appFileLocation=src/test/resources/appFolder/xyz.app
appium.automationType=XCUITest
appium.iosBrowserName=Safari
appium.autoAcceptAlerts=true
appium.useNewWda=true
appium.waitForIdleTimeout=0
appium.app=c:/demo.apk
appium.iosBundleId=com.Company.Qwerty
appium.iosXCodeOrgId=QAZ1234WSX
appium.iosXCodeSigningId=iPhone Developer
appium.iosUpdatedWdaBundleId=com.Company.Qwerty.WebDriverAgentRunner
appium.activateAppBundleId=com.Company.Qwerty.WebDriverAgentRunner
appium.showIosLog=true
mobile.isTouchIdAdded=false