proxyHost=proxy.applepersonatomcar.elephanttarzenneutral.com
proxyPort=8080
runLocally=Yes
environment.filepath=.//src//test/resources//environments//
apiExpectedBody.filePath=.//src//test/resources//data//output//ExpectedResponseBody//
apiRequestBody.filePath=.//src//test/resources//data//input//apiRequestBody//