name: API Automated Tests

on:
  workflow_dispatch:

jobs:
  api-automated-tests:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: '8.0.392'

      - name: Check JAVA_HOME
        run: |
          echo "JAVA_HOME is set to: $JAVA_HOME"
          java -version

      - name: Setup Maven
        shell: powershell
        run: |
         $mavenVersion = "3.9.6"
         $mavenUrl = "https://downloads.apache.org/maven/maven-3/$mavenVersion/binaries/apache-maven-$mavenVersion-bin.zip"
         $mavenDir = "$env:USERPROFILE\maven"
         Invoke-WebRequest -Uri $mavenUrl -OutFile "maven.zip"
         Expand-Archive -Path "maven.zip" -DestinationPath $mavenDir -Force
         $mavenBin = "$mavenDir\apache-maven-$mavenVersion\bin"
         echo "MAVEN_HOME = $mavenBin" >> $env:GITHUB_ENV
         echo "$mavenBin" >> $env:GITHUB_PATH
         mvn --version

      - name: Ensure Maven Repository Exists
        run: mkdir -p ~/.m2/repository
      
      - name: Debug Repository Path
        shell: pwsh
        run: Get-ChildItem -Path "~/.m2/"

      - name: Cache Maven
        uses: actions/cache@4.2.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml')}}
          restore-keys: ${{ runner.os }}-maven- 
         
