name: API Automated Tests

on:
  workflow_dispatch:

jobs:
  api-automated-tests:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'zulu'
          java-version: '8.0.392'

      - name: Check JAVA_HOME
        run: |
          echo "JAVA_HOME is set to: $JAVA_HOME"
          java -version

      - name: Setup Maven
        shell: powershell
        run: |
         $mavenVersion = "3.9.10"
         $mavenUrl = "https://downloads.apache.org/maven/maven-3/$mavenVersion/binaries/apache-maven-$mavenVersion-bin.zip"
         $mavenDir = "$env:USERPROFILE\maven"
         Invoke-WebRequest -Uri $mavenUrl -OutFile "maven.zip"
         Expand-Archive -Path "maven.zip" -DestinationPath $mavenDir -Force
         $mavenBin = "$mavenDir\apache-maven-$mavenVersion\bin"
         echo "MAVEN_HOME = $mavenBin" >> $env:GITHUB_ENV
         echo "$mavenBin" >> $env:GITHUB_PATH
         mvn --version

      - name: Ensure Maven Repository Exists
        run: mkdir -p ~/.m2/repository
      
      - name: Debug Repository Path
        shell: pwsh
        run: Get-ChildItem -Path "~/.m2/"

      - name: Cache Maven
        uses: actions/cache@4.2.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml')}}
          restore-keys: ${{ runner.os }}-maven- 

      - name: Remove Proxy
        shell: powershell
        run: |
          if(Test-Path settings.xml){
            try{
            $xml = [xml](Get-Content -Raw settings.xml)
            if($xml.settings.proxies){
             $xml.settings.RemoveChild($xml.settings.proxies) | Out-Null
             $xml.Save((Resolve-Path settings.xml))
            }
            }catch{
            Write-Error "Failed to parse or modify settings.xml: $_"
            exit 1
            }
          }else{
          Write-Error "setting.xml not found"
          exit 1
          }
          
      - name: Run API Automated Tests
        shell: cmd
        run: |
          echo mvn clean install -DexeEnvironment=QA -s settings.xml -Dmetafilter="+API1 +Action" -DstoryName="**/stories/WebAPI/**/*.story"
          mvn -X clean verify -DexeEnvironment=QA -s settings.xml -Dmetafilter="+API1 +Action" -DstoryName="**/stories/WebAPI/**/*.story" > api-test-output.txt
          if not exist api-test-output.txt {
          echo Output file not created
          exit 1
          }
          findstr "BUILD FAILURE" api-test-output.txt
          if %ERRORLEVEL% equ 0 {
          echo Build Failed
          exist 1
          }
          
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows/bash@v2.15.0
        if: always()
        with:
           files: target/failsafe-report/TEST*.xml
        continue-on-error: true

      - name: Archive Serenity Reports
        uses: actions/upload-artifact@v4.3.6
        if: always()
        with:
           name: api-tests-result
           path: target/site/serenity
        continue-on-error: true

      - name: Upload Test Output
        uses: actions/upload-artifact@v4.3.6
        if: always()
        with:
           name: api-test-output
           path: api-test-output.txt
        continue-on-error: true

      - name: Send Email via SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_SENDER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Automated Test Report"
          body: "Test report attached."
          to: ${{ secrets.RECIPIENTS }}
          from: ${{ secrets.EMAIL_SENDER }}
          attachments: "target/site/serenity/index.html"

